# DDL for the MOH 711 datalake tables.
# Run once (idempotent) before deploying / calling etl.generate_flat_moh_711_v1.
#
# - flat_moh_711_report: static mirror of the CREATE TABLE the procedure
#   issues dynamically; kept byte-identical so the procedure's
#   CREATE TABLE IF NOT EXISTS no-ops when this script has run first.
# - flat_moh_711_report_build_queue: master build queue consumed by
#   build mode ('CALL etl.generate_flat_moh_711_v1("build", ...)').
#   Nothing else creates it - populate it with the person_ids to
#   (re)build, then run the procedure in build mode.
# - flat_moh_711_report_sync_queue: also auto-created by the procedure;
#   defined here so the whole 711 table family lives in one file.
#
# Remaining dependencies (defined elsewhere, not duplicated here):
#   etl.flat_obs     -> etl-scripts/stored-procedures/datalake/generate_flat_obs.sql
#   etl.flat_log     -> etl-scripts/flat_tables/flat_log_v1.0.sql
#   etl.GetValues    -> etl-scripts/stored-procedures/datalake/getValues.sql
#   amrs.person / amrs.encounter -> OpenMRS source schema

create table if not exists flat_moh_711_report (

        date_created                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        person_id                      INT,
        uuid                           VARCHAR(100),
        encounter_id                   INT,
        encounter_datetime             DATETIME,
        encounter_type                 INT,
        location_id                    INT,
        birth_date                     DATE,
        gender                         VARCHAR(10),

        -- ANC (encounter types 264, 265)
        new_anc_clients                VARCHAR(5),
        revisit_anc_clients            VARCHAR(5),
        first_ipt_dose                 VARCHAR(5),
        second_ipt_dose                VARCHAR(5),
        third_ipt_dose                 VARCHAR(5),
        Hb_less_11g                    VARCHAR(5),
        first_anc_contact_12_or_less_weeks VARCHAR(5),
        completing_4_anc_visits        VARCHAR(5),
        completing_8_anc_contact       VARCHAR(5),
        llins_children_less_than_one   VARCHAR(5),
        llins_anc_clients              VARCHAR(5),
        anc_clients_tested_syphilis    VARCHAR(5),
        syphilis_positive              VARCHAR(5),
        breast_exam                    VARCHAR(5),
        adolesc_10_14                  VARCHAR(5),
        adolesc_15_19                  VARCHAR(5),
        youth_20_24                    VARCHAR(5),
        iron                           VARCHAR(5),
        folic                          VARCHAR(5),
        iron_and_folate                VARCHAR(5),
        fgm_complications              VARCHAR(5),

        -- SGBV (encounter types 56, 57, 133, 134, 264, 265, 179)
        sgbv_total_survivors_0_9       VARCHAR(5),
        sgbv_total_survivors_10_17     VARCHAR(5),
        sgbv_total_survivors_18_49     VARCHAR(5),
        sgbv_total_survivors_50_plus   VARCHAR(5),
        sgbv_within_72_hours_0_9       VARCHAR(5),
        sgbv_within_72_hours_10_17     VARCHAR(5),
        sgbv_within_72_hours_18_49     VARCHAR(5),
        sgbv_within_72_hours_50_above  VARCHAR(5),
        sgbv_initiated_on_pep_0_9      VARCHAR(5),
        sgbv_initiated_on_pep_10_17    VARCHAR(5),
        sgbv_initiated_on_pep_18_49    VARCHAR(5),
        sgbv_initiated_on_pep_50_above VARCHAR(5),
        sgbv_completed_pep_0_9         VARCHAR(5),
        sgbv_completed_pep_10_17       VARCHAR(5),
        sgbv_completed_pep_18_49       VARCHAR(5),
        sgbv_completed_pep_50_above    VARCHAR(5),
        sgbv_seroconverting_0_9        VARCHAR(5),
        sgbv_seroconverting_10_17      VARCHAR(5),
        sgbv_seroconverting_18_49      VARCHAR(5),
        sgbv_seroconverting_50_above   VARCHAR(5),
        sgbv_eligible_for_ecp_0_9      VARCHAR(5),
        sgbv_eligible_for_ecp_10_17    VARCHAR(5),
        sgbv_eligible_for_ecp_18_49    VARCHAR(5),
        sgbv_eligible_for_ecp_50_above VARCHAR(5),
        sgbv_receiving_ecp_0_9         VARCHAR(5),
        sgbv_receiving_ecp_10_17       VARCHAR(5),
        sgbv_receiving_ecp_18_49       VARCHAR(5),
        sgbv_receiving_ecp_50_above    VARCHAR(5),
        sgbv_pregnant_0_9              VARCHAR(5),
        sgbv_pregnant_10_17            VARCHAR(5),
        sgbv_pregnant_18_49            VARCHAR(5),
        sgbv_pregnant_50_above         VARCHAR(5),
        sgbv_rc_seen_0_9               VARCHAR(5),
        sgbv_rc_seen_10_17             VARCHAR(5),
        sgbv_rc_seen_18_49             VARCHAR(5),
        sgbv_rc_seen_50_above          VARCHAR(5),
        sgbv_with_disability_0_9       VARCHAR(5),
        sgbv_with_disability_10_17     VARCHAR(5),
        sgbv_with_disability_18_49     VARCHAR(5),
        sgbv_with_disability_50_above  VARCHAR(5),

        -- Maternity / Delivery (encounter types 196, 269, 273, 274)
        normal_deliveries              VARCHAR(5),
        caesarian_sections             VARCHAR(5),
        breach_delivery                VARCHAR(5),
        assisted_vaginal_delivery      VARCHAR(5),
        oxytocin_uterotonic            VARCHAR(5),
        carbatocin_uterotonic          VARCHAR(5),
        live_birth                     VARCHAR(5),
        low_birth_weight               VARCHAR(5),
        low_apgar_score                VARCHAR(5),
        birth_with_deformity           VARCHAR(5),
        chlorhexidine_applied          VARCHAR(5),
        vitamin_k                      VARCHAR(5),
        tetracycline_given             VARCHAR(5),
        pre_term_babies                VARCHAR(5),
        discharge_alive                VARCHAR(5),
        bf_within_1_hour               VARCHAR(5),
        deliveries_from_positive_women VARCHAR(5),
        fresh_still_birth              VARCHAR(5),
        macerated_still_birth          VARCHAR(5),
        perinatal_deaths_0_7_days      VARCHAR(5),
        neonatal_deaths_0_28_days      VARCHAR(5),
        maternal_deaths_10_14_years    VARCHAR(5),
        maternal_deaths_15_19_years    VARCHAR(5),
        maternal_deaths_20_24_years    VARCHAR(5),
        maternal_deaths_25_above_years VARCHAR(5),
        maternal_deaths_audited_within_7_days VARCHAR(5),
        neonatal_deaths_audited_within_7_days VARCHAR(5),
        ante_partum_haemorrage         VARCHAR(5),
        post_partum_haemorrage         VARCHAR(5),
        eclampsia                      VARCHAR(5),
        ruptured_uterus                VARCHAR(5),
        obstructed_labour              VARCHAR(5),
        sepsis                         VARCHAR(5),
        fgm_delivery_complications     VARCHAR(5),
        neonatal_deaths_sepsis         VARCHAR(5),
        neonatal_deaths_prematurity    VARCHAR(5),
        neonatal_deaths_asphyxia       VARCHAR(5),
        kangaroo_mother_care           VARCHAR(5),
        referrals_from_other_health_facility VARCHAR(5),
        referrals_to_other_health_facility   VARCHAR(5),
        referrals_from_community       VARCHAR(5),
        referrals_to_community         VARCHAR(5),

        -- Cervical Cancer Screening (encounter type 69)
        via_villi_hpv_less_25          VARCHAR(5),
        via_villi_hpv_25_49            VARCHAR(5),
        via_villi_hpv_50_above         VARCHAR(5),
        pap_smear_less_25              VARCHAR(5),
        pap_smear_25_49                VARCHAR(5),
        pap_smear_50_above             VARCHAR(5),
        hpv_test_less_25               VARCHAR(5),
        hpv_test_25_49                 VARCHAR(5),
        hpv_test_50_above              VARCHAR(5),
        positive_via_villi_less_25     VARCHAR(5),
        positive_via_villi_25_49       VARCHAR(5),
        positive_via_villi_50_above    VARCHAR(5),
        positive_cytology_less_25      VARCHAR(5),
        positive_cytology_25_49        VARCHAR(5),
        positive_cytology_50_above     VARCHAR(5),
        positive_hpv_less_25           VARCHAR(5),
        positive_hpv_25_49             VARCHAR(5),
        positive_hpv_50_above          VARCHAR(5),
        suspicious_cancer_lessions_less_25 VARCHAR(5),
        suspicious_cancer_lessions_25_49   VARCHAR(5),
        suspicious_cancer_lessions_50_above VARCHAR(5),
        cryotherapy_treatment_less_25  VARCHAR(5),
        cryotherapy_treatment_25_49    VARCHAR(5),
        cryotherapy_treatment_50_above VARCHAR(5),
        leep_treatment_less_25         VARCHAR(5),
        leep_treatment_25_49           VARCHAR(5),
        leep_treatment_50_above        VARCHAR(5),
        hiv_positive_screened_cervical_cancer_less_25 VARCHAR(5),
        hiv_positive_screened_cervical_cancer_25_49   VARCHAR(5),
        hiv_positive_screened_cervical_cancer_50_above VARCHAR(5),

        -- Family Planning (encounter type 179)
        first_users_contraceptive_new          VARCHAR(5),
        first_users_contraceptive_revisit      VARCHAR(5),
        pills_progestine_new                   VARCHAR(5),
        pills_progestine_revisit               VARCHAR(5),
        pills_combined_oral_contraceptive_new  VARCHAR(5),
        pills_combined_oral_contraceptive_revisit VARCHAR(5),
        emergency_contraceptive_pill_new       VARCHAR(5),
        emergency_contraceptive_pill_revisit   VARCHAR(5),
        fp_injections_dmpa_im                  VARCHAR(5),
        fp_injections_dmpa_sc                  VARCHAR(5),
        male_condoms_new                       VARCHAR(5),
        male_condoms_revisit                   VARCHAR(5),
        female_condoms_new                     VARCHAR(5),
        female_condoms_revisit                 VARCHAR(5),
        male_and_female_condoms_new            VARCHAR(5),
        male_and_female_condoms_revisit        VARCHAR(5),
        counselled_for_natural_family_planning_new    VARCHAR(5),
        counselled_for_natural_family_planning_revisit VARCHAR(5),
        cycle_beads_new                        VARCHAR(5),
        cycle_beads_revisit                    VARCHAR(5),
        implants_insertion_1_rod               VARCHAR(5),
        implants_insertion_2_rod               VARCHAR(5),
        iucd_hormonal                          VARCHAR(5),
        iucd_non_hormonal                      VARCHAR(5),
        surgical_contraception_btl             VARCHAR(5),
        vasectomy                              VARCHAR(5),
        iucd_removals                          VARCHAR(5),
        implants_removal                       VARCHAR(5),
        fp_adolescent_10_14_new                VARCHAR(5),
        fp_adolescent_10_14_revisit            VARCHAR(5),
        fp_adolescent_15_19_new                VARCHAR(5),
        fp_adolescent_15_19_revisit            VARCHAR(5),
        fp_adolescent_20_24_new                VARCHAR(5),
        fp_adolescent_20_24_revisit            VARCHAR(5),
        fp_adolescent_25_plus_new              VARCHAR(5),
        fp_adolescent_25_plus_revisit          VARCHAR(5),
        post_partum_fp_48_hours_new            VARCHAR(5),
        post_partum_fp_48_hours_revisit        VARCHAR(5),
        post_partum_fp_4_6_weeks_new           VARCHAR(5),
        post_partum_fp_4_6_weeks_revisit       VARCHAR(5),
        post_abortion_fp_new                   VARCHAR(5),
        post_abortion_fp_revisit               VARCHAR(5),

        -- PNC (encounter types 266, 267)
        pnc_new_clients                       VARCHAR(5),
        pnc_revisit_clients                   VARCHAR(5),
        women_couselled_on_post_partum_fp     VARCHAR(5),
        women_received_post_partum_fp         VARCHAR(5),
        mothers_post_partum_care_48_hours     VARCHAR(5),
        mothers_post_partum_care_3_6_weeks    VARCHAR(5),
        mothers_post_partum_care_after_6_weeks VARCHAR(5),
        infants_post_partum_care_48_hours     VARCHAR(5),
        infants_post_partum_care_3_6_weeks    VARCHAR(5),
        infants_post_partum_care_after_6_weeks VARCHAR(5),
        fistula_cases                         VARCHAR(5),
        pnc_referrals_from_community          VARCHAR(5),

        -- Psychosocial / Social Work (encounter types 1, 2)
        psycho_social_counselling             VARCHAR(5),
        alcohol_and_drug_abuse                VARCHAR(5),
        mental_illness                        VARCHAR(5),
        adolescent_issues                     VARCHAR(5),
        psycho_social_economic_assessment     VARCHAR(5),
        social_investigations                 VARCHAR(5),
        psycho_social_rehabilitation          VARCHAR(5),
        outreach_services                     VARCHAR(5),
        mental_health_referral                VARCHAR(5),

        -- TB Screening (encounter types 1, 2, 264, 265, 266, 267)
        total_screened_for_tb                 VARCHAR(5),
        total_presumptive_tb_cases            VARCHAR(5),
        already_on_tb_treatment               VARCHAR(5),
        not_screened_for_tb                   VARCHAR(5),

        -- Child Welfare / Nutrition - chanis (encounter types 4, 110, 167, 313)
        normal_weight_0_6_months_male         VARCHAR(5),
        normal_weight_0_6_months_female       VARCHAR(5),
        underweight_0_6_months_male           VARCHAR(5),
        underweight_0_6_months_female         VARCHAR(5),
        severely_underweight_0_6_months_male  VARCHAR(5),
        severely_underweight_0_6_months_female VARCHAR(5),
        overweight_0_6_months_male            VARCHAR(5),
        overweight_0_6_months_female          VARCHAR(5),
        obese_0_6_months_male                 VARCHAR(5),
        obese_0_6_months_female               VARCHAR(5),
        normal_weight_6_23_months_male        VARCHAR(5),
        normal_weight_6_23_months_female      VARCHAR(5),
        underweight_6_23_months_male          VARCHAR(5),
        underweight_6_23_months_female        VARCHAR(5),
        severely_underweight_6_23_months_male VARCHAR(5),
        severely_underweight_6_23_months_female VARCHAR(5),
        overweight_6_23_months_male           VARCHAR(5),
        overweight_6_23_months_female         VARCHAR(5),
        obese_6_23_months_male                VARCHAR(5),
        obese_6_23_months_female              VARCHAR(5),
        normal_weight_24_59_months_male       VARCHAR(5),
        normal_weight_24_59_months_female     VARCHAR(5),
        underweight_24_59_months_male         VARCHAR(5),
        underweight_24_59_months_female       VARCHAR(5),
        severely_underweight_24_59_months_male VARCHAR(5),
        severely_underweight_24_59_months_female VARCHAR(5),
        overweight_24_59_months_male          VARCHAR(5),
        overweight_24_59_months_female        VARCHAR(5),
        obese_24_59_months_male               VARCHAR(5),
        obese_24_59_months_female             VARCHAR(5),
        muac_6_59_months_normal_male          VARCHAR(5),
        muac_6_59_months_normal_female        VARCHAR(5),
        muac_6_59_months_moderate_male        VARCHAR(5),
        muac_6_59_months_moderate_female      VARCHAR(5),
        muac_6_59_months_severe_male          VARCHAR(5),
        muac_6_59_months_severe_female        VARCHAR(5),
        height_for_age_0_6_months_normal_male VARCHAR(5),
        height_for_age_0_6_months_normal_female VARCHAR(5),
        stunted_0_6_months_male               VARCHAR(5),
        stunted_0_6_months_female             VARCHAR(5),
        severely_stunted_0_6_months_male      VARCHAR(5),
        severely_stunted_0_6_months_female    VARCHAR(5),
        normal_height_for_age_6_23_months_male VARCHAR(5),
        normal_height_for_age_6_23_months_female VARCHAR(5),
        stunted_6_23_months_male              VARCHAR(5),
        stunted_6_23_months_female            VARCHAR(5),
        severely_stunted_6_23_months_male     VARCHAR(5),
        severely_stunted_6_23_months_female   VARCHAR(5),
        normal_height_for_age_24_59_months_male VARCHAR(5),
        normal_height_for_age_24_59_months_female VARCHAR(5),
        stunted_24_59_months_male             VARCHAR(5),
        stunted_24_59_months_female           VARCHAR(5),
        severely_stunted_24_59_months_male    VARCHAR(5),
        severely_stunted_24_59_months_female  VARCHAR(5),
        new_visits_0_59_months_attending_cwc_male   VARCHAR(5),
        new_visits_0_59_months_attending_cwc_female VARCHAR(5),
        kwashiokor_0_59_months_male           VARCHAR(5),
        kwashiokor_0_59_months_female         VARCHAR(5),
        marasmus_0_59_months_male             VARCHAR(5),
        marasmus_0_59_months_female           VARCHAR(5),
        faltering_growth_0_59_months_male     VARCHAR(5),
        faltering_growth_0_59_months_female   VARCHAR(5),
        exclusive_breastfeeding_0_6_months_male VARCHAR(5),
        exclusive_breastfeeding_0_6_months_female VARCHAR(5),
        dewormed_12_59_months_male            VARCHAR(5),
        dewormed_12_59_months_female          VARCHAR(5),
        mnps_supplimentation_6_23_months_male VARCHAR(5),
        mnps_supplimentation_6_23_months_female VARCHAR(5),
        diarhoea_severe_dehydration_male      VARCHAR(5),
        diarhoea_severe_dehydration_female    VARCHAR(5),
        diarhoea_some_dehydration_male        VARCHAR(5),
        diarhoea_some_dehydration_female      VARCHAR(5),
        diarhoea_no_dehydration_male          VARCHAR(5),
        diarhoea_no_dehydration_female        VARCHAR(5),
        diarhoea_treated_with_ors_zinc_dehydration_male   VARCHAR(5),
        diarhoea_treated_with_ors_zinc_dehydration_female VARCHAR(5),
        under_five_pneumomia_male             VARCHAR(5),
        under_five_pneumomia_female           VARCHAR(5),
        under_five_deaths_male                VARCHAR(5),
        under_five_deaths_female              VARCHAR(5),
        under_five_disability_male            VARCHAR(5),
        under_five_disability_female          VARCHAR(5),
        under_five_delayed_development_male   VARCHAR(5),
        under_five_delayed_development_female VARCHAR(5),

        PRIMARY KEY encounter_id (encounter_id),
        INDEX person_date (person_id, encounter_datetime),
        INDEX person_uuid (uuid),
        INDEX location (location_id)
);

create table if not exists flat_moh_711_report_build_queue (
    person_id INT PRIMARY KEY
);

create table if not exists flat_moh_711_report_sync_queue (
    person_id INT PRIMARY KEY
);
