# DDL for the MOH 717 datalake tables.
# Run once (idempotent) before deploying / calling etl.generate_flat_moh_717_v1.
#
# - flat_moh_717_report: static mirror of the CREATE TABLE the procedure
#   issues dynamically; kept byte-identical so the procedure's
#   CREATE TABLE IF NOT EXISTS no-ops when this script has run first.
# - flat_moh_717_report_build_queue: master build queue consumed by
#   build mode ('CALL etl.generate_flat_moh_717_v1("build", ...)').
#   Nothing else creates it - populate it with the person_ids to
#   (re)build, then run the procedure in build mode.
# - flat_moh_717_report_sync_queue: also auto-created by the procedure;
#   defined here so the whole 717 table family lives in one file.
#
# Remaining dependencies (defined elsewhere, not duplicated here):
#   etl.flat_obs     -> etl-scripts/stored-procedures/datalake/generate_flat_obs.sql
#   etl.flat_log     -> etl-scripts/flat_tables/flat_log_v1.0.sql
#   etl.GetValues    -> etl-scripts/stored-procedures/datalake/getValues.sql
#   amrs.person / amrs.encounter -> OpenMRS source schema

create table if not exists flat_moh_717_report (

        date_created                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        person_id                      INT,
        uuid                           VARCHAR(100),
        encounter_id                   INT,
        encounter_datetime             DATETIME,
        encounter_type                 INT,
        location_id                    INT,
        birth_date                     DATE,
        gender                         VARCHAR(10),


        -- General Outpatient (encounter type 167)
        opd_attendance_greater_5yrs_male_new                  VARCHAR(5),
        opd_attendance_greater_5yrs_male_revisit              VARCHAR(5),
        opd_attendance_greater_5yrs_female_new                VARCHAR(5),
        opd_attendance_greater_5yrs_female_revisit            VARCHAR(5),
        opd_attendance_less_5yrs_male_new                     VARCHAR(5),
        opd_attendance_less_5yrs_male_revisit                 VARCHAR(5),
        opd_attendance_less_5yrs_female_new                   VARCHAR(5),
        opd_attendance_less_5yrs_female_revisit               VARCHAR(5),
        over_60_years_new                                     VARCHAR(5),
        over_60_years_revisit                                 VARCHAR(5),
        casualty_attendance_new                               VARCHAR(5),
        casualty_attendance_revisit                           VARCHAR(5),

        -- Special Clinics (encounter types 1, 2, 38, 39, 168)
        ent_clinic_attendance_new                             VARCHAR(5),
        ent_clinic_attendance_revisit                         VARCHAR(5),
        eye_clinic_attendance_new                             VARCHAR(5),
        eye_clinic_attendance_revisit                         VARCHAR(5),
        tb_and_leprosy_attendance_new                         VARCHAR(5),
        tb_and_leprosy_attendance_revisit                     VARCHAR(5),
        ccc_new                                               VARCHAR(5),
        ccc_revisit                                           VARCHAR(5),
        psychiatry_attendance_new                             VARCHAR(5),
        psychiatry_attendance_revisit                         VARCHAR(5),
        orthopaedic_new                                       VARCHAR(5),
        orthopaedic_revisit                                   VARCHAR(5),
        occupational_therapy_new                              VARCHAR(5),
        occupational_therapy_revisit                          VARCHAR(5),
        physiotherapy_new                                     VARCHAR(5),
        physiotherapy_revisit                                 VARCHAR(5),
        medical_attendance_new                                VARCHAR(5),
        medical_attendance_revisit                            VARCHAR(5),
        surgical_clinics_new                                  VARCHAR(5),
        surgical_clinics_revisit                              VARCHAR(5),
        paediatrics_attendance_new                            VARCHAR(5),
        paediatrics_attendance_revisit                        VARCHAR(5),
        obstetrics_gynaecology_new                            VARCHAR(5),
        obstetrics_gynaecology_revisit                        VARCHAR(5),
        nutrition_new                                         VARCHAR(5),
        nutrition_revisit                                     VARCHAR(5),
        oncology_new                                          VARCHAR(5),
        oncology_revisit                                      VARCHAR(5),
        renal_new                                             VARCHAR(5),
        renal_revisit                                         VARCHAR(5),
        other_special_clinics_new                             VARCHAR(5),
        other_special_clinics_revisit                         VARCHAR(5),

        -- MCH / Family Planning (encounter types 179, 264, 265, 266, 267, 167)
        cwc_attendance_new                                    VARCHAR(5),
        cwc_attendance_revisit                                VARCHAR(5),
        anc_new                                               VARCHAR(5),
        anc_revisit                                           VARCHAR(5),
        pnc_new                                               VARCHAR(5),
        pnc_revisit                                           VARCHAR(5),
        fp_attendance_new                                     VARCHAR(5),
        fp_attendance_revisit                                 VARCHAR(5),

        -- Dental (encounter type 329)
        dental_attendance_ex_fillings_extractions_new         VARCHAR(5),
        dental_attendance_ex_fillings_extractions_revisit     VARCHAR(5),
        dental_fillings_new                                   VARCHAR(5),
        dental_fillings_revisit                               VARCHAR(5),
        dental_extractions_new                                VARCHAR(5),
        dental_extractions_revisit                            VARCHAR(5),

        -- Other Services - TODO upstream: all placeholders in the moh-717 json definitions
        medical_examinations_except_p3                        VARCHAR(5),
        opd_medical_reports                                   VARCHAR(5),
        opd_dressing_done                                     VARCHAR(5),
        opd_removal_of_stitches                               VARCHAR(5),
        opd_injections_given                                  VARCHAR(5),
        opd_stitching                                         VARCHAR(5),

        -- Inpatient wards - TODO upstream: all placeholders in the moh-717 json definitions
        medical_discharges                                    VARCHAR(5),
        surgical_discharges                                   VARCHAR(5),
        obst_gyn_discharges                                   VARCHAR(5),
        paediatrics_discharges                                VARCHAR(5),
        maternity_discharges                                  VARCHAR(5),
        eye_discharges                                        VARCHAR(5),
        nursery_newborn_discharges                            VARCHAR(5),
        orthopaedic_discharges                                VARCHAR(5),
        medical_deaths                                        VARCHAR(5),
        surgical_deaths                                       VARCHAR(5),
        obst_gyn_deaths                                       VARCHAR(5),
        paediatrics_deaths                                    VARCHAR(5),
        maternity_deaths                                      VARCHAR(5),
        eye_deaths                                            VARCHAR(5),
        nursery_newborn_deaths                                VARCHAR(5),
        orthopaedic_deaths                                    VARCHAR(5),
        medical_deaths_malaria                                VARCHAR(5),
        surgical_deaths_malaria                               VARCHAR(5),
        obst_gyn_deaths_malaria                               VARCHAR(5),
        paediatrics_deaths_malaria                            VARCHAR(5),
        maternity_deaths_malaria                              VARCHAR(5),
        eye_deaths_malaria                                    VARCHAR(5),
        nursery_newborn_deaths_malaria                        VARCHAR(5),
        orthopaedic_deaths_malaria                            VARCHAR(5),
        medical_abscondees                                    VARCHAR(5),
        surgical_abscondees                                   VARCHAR(5),
        obst_gyn_abscondees                                   VARCHAR(5),
        paediatrics_abscondees                                VARCHAR(5),
        maternity_abscondees                                  VARCHAR(5),
        eye_abscondees                                        VARCHAR(5),
        nursery_newborn_abscondees                            VARCHAR(5),
        orthopaedic_abscondees                                VARCHAR(5),
        medical_referrals_out_of_facility                     VARCHAR(5),
        surgical_referrals_out_of_facility                    VARCHAR(5),
        obst_gyn_referrals_out_of_facility                    VARCHAR(5),
        paediatrics_referrals_out_of_facility                 VARCHAR(5),
        maternity_referrals_out_of_facility                   VARCHAR(5),
        eye_referrals_out_of_facility                         VARCHAR(5),
        nursery_newborn_referrals_out_of_facility             VARCHAR(5),
        orthopaedic_referrals_out_of_facility                 VARCHAR(5),
        medical_admissions_0_28_days                          VARCHAR(5),
        surgical_admissions_0_28_days                         VARCHAR(5),
        obst_gyn_admissions_0_28_days                         VARCHAR(5),
        paediatrics_admissions_0_28_days                      VARCHAR(5),
        maternity_admissions_0_28_days                        VARCHAR(5),
        eye_admissions_0_28_days                              VARCHAR(5),
        nursery_newborn_admissions_0_28_days                  VARCHAR(5),
        orthopaedic_admissions_0_28_days                      VARCHAR(5),
        medical_admissions_under_five                         VARCHAR(5),
        surgical_admissions_under_five                        VARCHAR(5),
        obst_gyn_admissions_under_five                        VARCHAR(5),
        paediatrics_admissions_under_five                     VARCHAR(5),
        maternity_admissions_under_five                       VARCHAR(5),
        eye_admissions_under_five                             VARCHAR(5),
        nursery_newborn_admissions_under_five                 VARCHAR(5),
        orthopaedic_admissions_under_five                     VARCHAR(5),
        medical_admissions_over_five                          VARCHAR(5),
        surgical_admissions_over_five                         VARCHAR(5),
        obst_gyn_admissions_over_five                         VARCHAR(5),
        paediatrics_admissions_over_five                      VARCHAR(5),
        maternity_admissions_over_five                        VARCHAR(5),
        eye_admissions_over_five                              VARCHAR(5),
        nursery_newborn_admissions_over_five                  VARCHAR(5),
        orthopaedic_admissions_over_five                      VARCHAR(5),
        medical_admissions_under_five_severe_malaria          VARCHAR(5),
        surgical_admissions_under_five_severe_malaria         VARCHAR(5),
        obst_gyn_admissions_under_five_severe_malaria         VARCHAR(5),
        paediatrics_admissions_under_five_severe_malaria      VARCHAR(5),
        maternity_admissions_under_five_severe_malaria        VARCHAR(5),
        eye_admissions_under_five_severe_malaria              VARCHAR(5),
        nursery_newborn_admissions_under_five_severe_malaria  VARCHAR(5),
        orthopaedic_admissions_under_five_severe_malaria      VARCHAR(5),
        medical_admissions_over_five_severe_malaria           VARCHAR(5),
        surgical_admissions_over_five_severe_malaria          VARCHAR(5),
        obst_gyn_admissions_over_five_severe_malaria          VARCHAR(5),
        paediatrics_admissions_over_five_severe_malaria       VARCHAR(5),
        maternity_admissions_over_five_severe_malaria         VARCHAR(5),
        eye_admissions_over_five_severe_malaria               VARCHAR(5),
        nursery_newborn_admissions_over_five_severe_malaria   VARCHAR(5),
        orthopaedic_admissions_over_five_severe_malaria       VARCHAR(5),
        medical_paroles                                       VARCHAR(5),
        surgical_paroles                                      VARCHAR(5),
        obst_gyn_paroles                                      VARCHAR(5),
        paediatrics_paroles                                   VARCHAR(5),
        maternity_paroles                                     VARCHAR(5),
        eye_paroles                                           VARCHAR(5),
        nursery_newborn_paroles                               VARCHAR(5),
        orthopaedic_paroles                                   VARCHAR(5),
        medical_occupied_bed_days_sha_members                 VARCHAR(5),
        surgical_occupied_bed_days_sha_members                VARCHAR(5),
        obst_gyn_occupied_bed_days_sha_members                VARCHAR(5),
        paediatrics_occupied_bed_days_sha_members             VARCHAR(5),
        maternity_occupied_bed_days_sha_members               VARCHAR(5),
        eye_occupied_bed_days_sha_members                     VARCHAR(5),
        nursery_newborn_occupied_bed_days_sha_members         VARCHAR(5),
        orthopaedic_occupied_bed_days_sha_members             VARCHAR(5),
        medical_occupied_bed_days_non_sha_members             VARCHAR(5),
        surgical_occupied_bed_days_non_sha_members            VARCHAR(5),
        obst_gyn_occupied_bed_days_non_sha_members            VARCHAR(5),
        paediatrics_occupied_bed_days_non_sha_members         VARCHAR(5),
        maternity_occupied_bed_days_non_sha_members           VARCHAR(5),
        eye_occupied_bed_days_non_sha_members                 VARCHAR(5),
        nursery_newborn_occupied_bed_days_non_sha_members     VARCHAR(5),
        orthopaedic_occupied_bed_days_non_sha_members         VARCHAR(5),
        medical_well_persons_days                             VARCHAR(5),
        surgical_well_persons_days                            VARCHAR(5),
        obst_gyn_well_persons_days                            VARCHAR(5),
        paediatrics_well_persons_days                         VARCHAR(5),
        maternity_well_persons_days                           VARCHAR(5),
        eye_well_persons_days                                 VARCHAR(5),
        nursery_newborn_well_persons_days                     VARCHAR(5),
        orthopaedic_well_persons_days                         VARCHAR(5),
        medical_authorised_beds                               VARCHAR(5),
        surgical_authorised_beds                              VARCHAR(5),
        obst_gyn_authorised_beds                              VARCHAR(5),
        paediatrics_authorised_beds                           VARCHAR(5),
        maternity_authorised_beds                             VARCHAR(5),
        eye_authorised_beds                                   VARCHAR(5),
        nursery_newborn_authorised_beds                       VARCHAR(5),
        orthopaedic_authorised_beds                           VARCHAR(5),
        medical_actual_physical_beds                          VARCHAR(5),
        surgical_actual_physical_beds                         VARCHAR(5),
        obst_gyn_actual_physical_beds                         VARCHAR(5),
        paediatrics_actual_physical_beds                      VARCHAR(5),
        maternity_actual_physical_beds                        VARCHAR(5),
        eye_actual_physical_beds                              VARCHAR(5),
        nursery_newborn_actual_physical_beds                  VARCHAR(5),
        orthopaedic_actual_physical_beds                      VARCHAR(5),
        medical_authorised_cots                               VARCHAR(5),
        surgical_authorised_cots                              VARCHAR(5),
        obst_gyn_authorised_cots                              VARCHAR(5),
        paediatrics_authorised_cots                           VARCHAR(5),
        maternity_authorised_cots                             VARCHAR(5),
        eye_authorised_cots                                   VARCHAR(5),
        nursery_newborn_authorised_cots                       VARCHAR(5),
        orthopaedic_authorised_cots                           VARCHAR(5),
        medical_actual_physical_cots                          VARCHAR(5),
        surgical_actual_physical_cots                         VARCHAR(5),
        obst_gyn_actual_physical_cots                         VARCHAR(5),
        paediatrics_actual_physical_cots                      VARCHAR(5),
        maternity_actual_physical_cots                        VARCHAR(5),
        eye_actual_physical_cots                              VARCHAR(5),
        nursery_newborn_actual_physical_cots                  VARCHAR(5),
        orthopaedic_actual_physical_cots                      VARCHAR(5),
        medical_authorised_incubator                          VARCHAR(5),
        surgical_authorised_incubator                         VARCHAR(5),
        obst_gyn_authorised_incubator                         VARCHAR(5),
        paediatrics_authorised_incubator                      VARCHAR(5),
        maternity_authorised_incubator                        VARCHAR(5),
        eye_authorised_incubator                              VARCHAR(5),
        nursery_newborn_authorised_incubator                  VARCHAR(5),
        orthopaedic_authorised_incubator                      VARCHAR(5),
        medical_actual_Physical_incubator                     VARCHAR(5),
        surgical_actual_Physical_incubator                    VARCHAR(5),
        obst_gyn_actual_Physical_incubator                    VARCHAR(5),
        paediatrics_actual_Physical_incubator                 VARCHAR(5),
        maternity_actual_Physical_incubator                   VARCHAR(5),
        eye_actual_Physical_incubator                         VARCHAR(5),
        nursery_newborn_actual_Physical_incubator             VARCHAR(5),
        orthopaedic_actual_Physical_incubator                 VARCHAR(5),

        -- Maternity (encounter types 196, 269, 273, 274)
        normal_deliveries                                     VARCHAR(5),
        caesarean_sections                                    VARCHAR(5),
        breach_deliveries                                     VARCHAR(5),
        assisted_vaginal_deliveries                           VARCHAR(5),
        born_before_arrival                                   VARCHAR(5),
        maternal_deaths                                       VARCHAR(5),
        maternal_deaths_audited_within_7_days                 VARCHAR(5),
        live_births                                           VARCHAR(5),
        still_births                                          VARCHAR(5),
        neonatal_deaths_0_28_days                             VARCHAR(5),
        neonatal_deaths_audits                                VARCHAR(5),
        low_birth_weight_less_2500gms                         VARCHAR(5),
        babies_discharged_alive                               VARCHAR(5),

        -- Operations - TODO upstream: all placeholders in the moh-717 json definitions
        minor_surgeries_booked                                VARCHAR(5),
        minor_surgeries_operated                              VARCHAR(5),
        emergencies_booked                                    VARCHAR(5),
        emergencies_operated                                  VARCHAR(5),
        cold_cases_booked                                     VARCHAR(5),
        cold_surgical_cases                                   VARCHAR(5),
        circumcisions_booked                                  VARCHAR(5),
        circumcisions_operated                                VARCHAR(5),
        major_surgeries_booked                                VARCHAR(5),
        major_surgeries_operated                              VARCHAR(5),

        -- Orthopaedic Trauma - TODO upstream: all placeholders in the moh-717 json definitions
        casts_fixed_less_5_years_new                          VARCHAR(5),
        casts_fixed_less_5_years_revisit                      VARCHAR(5),
        casts_fixed_over_5_years_new                          VARCHAR(5),
        casts_fixed_over_5_years_revisit                      VARCHAR(5),
        tractions_fixed_less_5_years_new                      VARCHAR(5),
        tractions_fixed_less_5_years_revisit                  VARCHAR(5),
        tractions_fixed_over_5_years_new                      VARCHAR(5),
        tractions_fixed_over_5_years_revisit                  VARCHAR(5),
        closed_reductions_less_5_years_new                    VARCHAR(5),
        closed_reductions_less_5_years_revisit                VARCHAR(5),
        closed_reductions_over_5_years_new                    VARCHAR(5),
        closed_reductions_over_5_years_revisit                VARCHAR(5),
        orthopaedic_assisted_in_theatre_less_5_years_new      VARCHAR(5),
        orthopaedic_assisted_in_theatre_less_5_years_revisit  VARCHAR(5),
        orthopaedic_assisted_in_theatre_over_5_years_new      VARCHAR(5),
        orthopaedic_assisted_in_theatre_over_5_years_revisit  VARCHAR(5),
        club_foot_seen_less_5_years_new                       VARCHAR(5),
        club_foot_seen_less_5_years_revisit                   VARCHAR(5),
        club_foot_seen_over_5_years_new                       VARCHAR(5),
        club_foot_seen_over_5_years_revisit                   VARCHAR(5),
        crepe_bandages_applied_less_5_years_new               VARCHAR(5),
        crepe_bandages_applied_less_5_years_revisit           VARCHAR(5),
        crepe_bandages_applied_over_5_years_new               VARCHAR(5),
        crepe_bandages_applied_over_5_years_revisit           VARCHAR(5),

        -- Orthopaedic Removal - TODO upstream: all placeholders in the moh-717 json definitions
        removals_done_cast_less_5_years                       VARCHAR(5),
        removals_done_cast_over_5_years                       VARCHAR(5),
        removals_done_tractions_less_5_years                  VARCHAR(5),
        removals_done_tractions_over_5_years                  VARCHAR(5),
        ex_fixator_removed_less_5_years                       VARCHAR(5),
        ex_fixator_removed_over_5_years                       VARCHAR(5),

        -- Special Services - TODO upstream: all placeholders in the moh-717 json definitions
        lab_routine_test                                      VARCHAR(5),
        lab_special_test                                      VARCHAR(5),
        plain_xray_without_enhancement                        VARCHAR(5),
        contrast_enhancement_examination                      VARCHAR(5),
        magnetic_resonance_imaging                            VARCHAR(5),
        computerized_tomography                               VARCHAR(5),
        mammography                                           VARCHAR(5),
        chest_xray_for_ptb                                    VARCHAR(5),
        number_of_ultrasound_examinations                     VARCHAR(5),
        general_ultrasound                                    VARCHAR(5),
        obstetric_ultrasound                                  VARCHAR(5),
        total_routine_xray_and_imaging                        VARCHAR(5),
        total_special_exams_xray_and_imaging                  VARCHAR(5),
        physiotherapy_number_of_treatments                    VARCHAR(5),
        occupational_therapy_number_of_treatments             VARCHAR(5),
        orthopaedic_technology_prepared                       VARCHAR(5),
        orthopaedic_technology_issued                         VARCHAR(5),

        -- Pharmacy - TODO upstream: all placeholders in the moh-717 json definitions
        prescriptions_issued_common_drugs                     VARCHAR(5),
        prescriptions_issued_antibiotics                      VARCHAR(5),
        prescriptions_issued_special_drugs                    VARCHAR(5),
        prescriptions_issued_drugs_children                   VARCHAR(5),

        -- Mortuary - TODO upstream: all placeholders in the moh-717 json definitions
        mortuary_body_days                                    VARCHAR(5),
        mortuary_embalment                                    VARCHAR(5),
        mortuary_postmortem                                   VARCHAR(5),
        mortuary_unclaimed_bodies                             VARCHAR(5),

        -- Medical Records - TODO upstream: all placeholders in the moh-717 json definitions
        new_patient_files_issued                              VARCHAR(5),
        outpatient_records_cards_issued                       VARCHAR(5),

        PRIMARY KEY encounter_id (encounter_id),
        INDEX person_date (person_id, encounter_datetime),
        INDEX person_uuid (uuid),
        INDEX location (location_id)
);

create table if not exists flat_moh_717_report_build_queue (
    person_id INT PRIMARY KEY
);

create table if not exists flat_moh_717_report_sync_queue (
    person_id INT PRIMARY KEY
);
