version: '2'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # volumes:
        #     - ./airflow/db:/var/lib/postgresql/data

    airflow:
        build:
            context: ./airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./etl-scripts:/usr/local/airflow/etl-scripts:ro
            - ./airflow/email-templates/:/usr/local/airflow/email-templates
            - ./airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            # - ./jars:/usr/local/airflow/spark-jars:ro
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - 8092:8080
        command: webserver
        #healthcheck:
        #    test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        #    interval: 30s
        #    timeout: 30s
        #    retries: 3
