#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
#git pull
mysql -u$(< /run/secrets/etl_user)  -p$(< /run/secrets/etl_password) etl < ../calculated_tables/defaulters_v2.3.sql
