#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"

mysql -u$(< /run/secrets/etl_user) -p$(< /run/secrets/etl_password) etl < ./sync_hiv_monthly_set.sql
#mysql -u$(< /run/secrets/etl_user) -p$(< /run/secrets/etl_password) etl < ./sync_cdm_monthly_set.sql
