#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
#git pull
mysql etl < drop_etl_tables.sql
mysql etl < ../flat_tables/flat_log_v1.0.sql
mysql etl < ../flat_tables/flat_obs_v1.1.sql
mysql etl < ../flat_tables/flat_lab_obs_v1.1.sql
mysql etl < ../calculated_tables/hiv_summary_v2.3.sql
mysql etl < ../calculated_tables/labs_and_imaging_v2.2.sql
mysql etl < ../calculated_tables/vitals_v2.0.sql
mysql etl < ../calculated_tables/derived_encounter.sql
mysql etl < ../calculated_tables/defaulters_v2.0.sql
mysql etl < ../calculated_tables/cohort_dates.sql
