#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
#git pull
mysql etl < ../flat_tables/flat_obs.sql
mysql etl < ../flat_tables/flat_orders.sql
mysql etl < ../flat_tables/flat_lab_obs.sql
mysql etl < ../calculated_tables/hiv_summary.sql
mysql etl < ../calculated_tables/labs_and_imaging.sql
mysql etl < ../calculated_tables/vitals.sql
mysql etl < ../calculated_tables/hiv_vl_summary.sql
mysql etl < ../calculated_tables/pep_summary.sql

