#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
#git pull
mysql -u$(< /run/secrets/etl_user) -p$(< /run/secrets/etl_password) etl < ../flat_tables/flat_obs_v1.1.sql
mysql -u$(< /run/secrets/etl_user) -p$(< /run/secrets/etl_password) etl < ../flat_tables/flat_lab_obs_v1.1.sql
