#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
#git pull
mysql etl < ../flat_tables/flat_obs.sql
mysql etl < ../flat_tables/flat_lab_obs.sql
mysql etl < ../calculated_tables/hiv_summary_v2.0.sql
mysql etl < ../calculated_tables/labs_and_imaging_v2.0.sql
mysql etl < ../calculated_tables/vitals.sql
